"""newsletter.target_time

Revision ID: 556eade48481
Revises: 864ebd0009a9
Create Date: 2024-05-05 18:27:26.682253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '556eade48481'
down_revision: Union[str, None] = '864ebd0009a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter', sa.Column('target_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newsletter', 'target_time')
    # ### end Alembic commands ###
